import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="Ferret Rescue Webpage" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.homeContainer}>
        <div className={styles.aboutUsContainer}>
          <h1>About Us</h1>
          <p className={styles.para}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus, sunt? Officiis at possimus incidunt dolorum. Explicabo, beatae recusandae, repellat reiciendis, odit voluptatibus tempora libero sint nostrum ullam soluta voluptas incidunt?</p>
          <p className={styles.para}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore soluta, recusandae iusto tenetur cum, pariatur perferendis commodi ut alias modi earum, iste consectetur quisquam accusantium perspiciatis beatae possimus magnam eos!</p>
          <p className={styles.para}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore soluta, recusandae iusto tenetur cum, pariatur perferendis commodi ut alias modi earum, iste consectetur quisquam accusantium perspiciatis beatae possimus magnam eos!</p>
        </div>
        <div>
          {/*<Image src={'/ferret-home.jpg'} alt={"ferret sable"} width={640} height={425} className={styles.img}/>*/}
          <img className={styles.img} src={'/ferret-home.jpg'} width="640" heigh="425" />
        </div>
      </section>
    </>
  )
}
